### ISSUE TITLE
Decode Protobufs? 

### ISSUE THREAD

**Issue by FredericJacobs** [SpinResearch/RustySecrets#11]
Protocol buffers could be the default deserialized structure. 

It could contain:
- [ ] A version of the result (if can't be parsed, suggest to update the software)
- [ ] Extension / MIME-Type of the data
- [ ] The actual data

Optional values such as generation date, a signature of a potential sender ...

**Comment by GabeIsman** [comment]
This seems like a good idea.

**Comment by FredericJacobs** [comment]
Implemented.
