### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by FredericJacobs** [SpinResearch/RustySecrets#12]
It appears that all **simple** solutions to do code coverage reporting with Travis appear to be broken. [Travis-Cargo](https://github.com/huonw/travis-cargo) broke and appears to be no longer maintained. I'm not willing to commit maintaining a fork of it at the moment, so for now I look at code coverage locally before merging pull requests.

This issue is a placeholder for a discussion about longer-term plans.

**Comment by romac** [comment]
Fixed in #41.
