### ISSUE TITLE
Build fail due to merkle v1.10.0

### ISSUE THREAD

**Issue by KallerTobias** [SpinResearch/RustySecrets#75]
The Build fail due to merkle v1.10.0:

```
   Compiling merkle v1.10.0
error: failed to run custom build command for `merkle v1.10.0`
process didn't exit successfully: `/Users/kaller/IdeaProjects/dssaa_s/target/debug/build/merkle-f78177df6eb47b03/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by romac** [comment]
1. Do you have protobuf installed? (`$ which protoc`)
2. If yes, which version? (`$ protoc --version`) merkle v.1.10.0 is know to work with protobuf 3.5.1 and 3.6.1

If that is indeed where the problem comes from, we are sorry about that!

I will update the README to let people know about the underlying protobuf dependency.

**Comment by KallerTobias** [comment]
I did install protocols 3.6.1  today.
But now there is another failure with merkle:

```
   Compiling merkle v1.10.0
error: failed to run custom build command for `merkle v1.10.0`
process didn't exit successfully: `/Users/kaller/IdeaProjects/dssaa_s/target/debug/build/merkle-f78177df6eb47b03/build-script-build` (exit code: 1)
--- stderr
Build failed because merkle.rs could not find: libprotoc 3.5.1

```

**Comment by romac** [comment]
Oh sorry I didn’t realise we were looking for this specific version. Can you try with 3.5.1?

**Comment by KallerTobias** [comment]
> Oh sorry I didn’t realise we were looking for this specific version. Can you try with 3.5.1?
> […](#)
> On 6 Mar 2019, at 18:35, KallerTobias ***@***.***> wrote: I did install protocols 3.6.1 now. But now there is another failure with merkle: Compiling merkle v1.10.0 error: failed to run custom build command for `merkle v1.10.0` process didn't exit successfully: `/Users/kaller/IdeaProjects/dssaa_s/target/debug/build/merkle-f78177df6eb47b03/build-script-build` (exit code: 1) --- stderr Build failed because merkle.rs could not find: libprotoc 3.5.1 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Thank you. It finally works with protobuf 3.5.1
